### ISSUE TITLE
[REFACTOR] 회원

### ISSUE THREAD

**Issue by somang-lim** [likelion-backendschool/FinalProject_LimSoMang_team7#5]
### 이슈내용
- 회원 관련 리팩토링

### 상세내용
- 권한 수정(ADMIN, AUTHOR, MEMBER → ADMIN, MEMBER)
- 일반 회원과 작가 회원 관련된 @PreAuthorize 설정 변경
- 유효성 검사 추가(Validation, BindingResult)
- 프론트 단에서 처리한 부분을 백엔드 단으로 옮기기 (ex. 비밀번호, 비밀번호 확인 일치 검사 등)
- controller과 service에서 처리할 내용 구분

### TODO
- [x] 로그인 시 권한 수정
- [x] 일반 회원과 작가 회원 관련된 @PreAuthorize 설정 변경
- [x] 유효성 검사 추가(Validation, BindingResult)
- [x] 프론트 단에서 처리한 부분을 백엔드 단으로 옮기기 (ex. 비밀번호, 비밀번호 확인 일치 검사 등)
- [x] controller과 service에서 처리할 내용 구분
- [x] 예외 처리 더 상세하게 구현
