### ISSUE TITLE
[FEATURE] 도서 - 1주차 추가과제

### ISSUE THREAD

**Issue by somang-lim** [likelion-backendschool/FinalProject_LimSoMang_team7#8]
### 이슈내용
- 상품(도서) CRUD

### 상세내용
- 상품 작성 · 수정
- 상품 리스트
- 상품 삭제
- 상품 상세화면

### TODO
- [x] Product Entity 추가

#### ✔️ 상품 작성 · 수정
- [x] 상품 이름을 작성할 수 있다.
- [x] 하나의 글 키워드만 고를 수 있다.
- [x] 등록을 누르면 해당 상품 상세페이지로 이동한다.
- [x] 키워드는 수정이 불가능하고 내용은 수정이 가능하다.

#### ✔️ 상품 리스트
- [x] 모든 상품을 출력한다.
- [x] 각각 상품은 상품의 이름, 가격, 작가를 출력한다.

#### ✔️ 상품 삭제
- [x] 상품이 삭제되면 상품 리스트로 리다이렉트 한다.
- [x] 삭제버튼을 눌렀을 때 confirm 창으로 삭제 여부를 한 번 더 물어본다.

#### ✔️ 상품 상세화면
- [x] 상품의 이름, 가격, 작가를 출력한다.
- [x] 상품 설명을 출력한다.
- [x] 미리보기는 구현하지 않는다.
